### PR TITLE
Release 63 to master

### PR DESCRIPTION
**Pull request by jedrichards**

### CODE REVIEW

**Comment by christianklotz** [comment]
Should this go into `master` first and then merge `master` into `develop`?

**Comment by jedrichards** [comment]
@christianklotz I'm not sure, what would be the benefit?

**Comment by christianklotz** [comment]
@jedrichards having the public release state on master. If there are no differences between `develop` and `master` then there won't be a problem but we certainly want the website to include latest release 🤔

**Comment by jedrichards** [comment]
@christianklotz I see what you mean, I switched the base branch.

**Pull request merged**
