### PR TITLE
Kevin/radio options

### PR DESCRIPTION
**Pull request by KevinGutowski**
[WIP]

From feedback in #316

By specifying the radio option variant for `INPUT_TYPE.selection` a developer can change the selection style.

Example:

Will need to pass extra parameter `radioStyle:true`

``` javascript
let UI = require('sketch').UI

UI.getInputFromUser("What's your favorite design tool?", {
  type: UI.INPUT_TYPE.selection,
  possibleValues: ['Something really long and aweful goes here and not sure what happens', 'Sketch', 'Hello'],
  radioStyle: true,
}, (err, value) => {
  if (err) {
    // most likely the user canceled the input
    console.error(err)
    return
  }
  console.log("selected value is: " + value)
})
```

Current concerns:

- [ ] Unsure what the best way to specify the UI type for selection (dropdown vs radio options). Want something that won’t break old code but allows for future expansion.
- [ ] Last? radio option can be highlighted
Sep-17-2019 01-32-13
- [ ] Had to disable linter warning on line [278](https://github.com/BohemianCoding/SketchAPI/compare/develop...KevinGutowski:kevin/radio_options?expand=1#diff-1165cabb99c47300408a4c1126da287fR278) Maybe try not using a for loop?
- [ ] Truncate clipped text

### CODE REVIEW

**Comment by bomberstudios** [comment]
This looks awesome, thanks a lot for taking the time to build it!

We'll take a look at this when we have a minute (we're a bit busy with the 58 release at the moment 😅 )

**Comment by KevinGutowski** [comment]
No worries! I’ll be cleaning it up a bit more over the next few days. I realized that I should probably extend this to also support a multiselect with checkboxes which slightly changes how I imagine interacting with the API should look like.

**Comment by jedrichards** [comment]
@KevinGutowski I only found out about them myself recently, but the new(ish) [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/) seem like a nice way to handle a PR in progress like this, avoiding the manual "WIP" labels and so on.

**Comment by KevinGutowski** [comment]
Ahh thanks for the tip! I'll try that out. Mostly wanted to get this PR out so that others might be able to point me in the right direction.

**Comment by jedrichards** [comment]
@KevinGutowski Done some spring cleaning in the repo and updated some dependencies. You might want to update vs. `develop` - not sure where your package-lock conflict is coming from.

The `no-plusplus` eslint rule seems a bit silly to me, feel free to disable it in the main eslintrc file. Otherwise you could just rewrite your loop definition without using `++`?

```
for (let i = 0; i < accessory.subviews().length; i=i+1) {
```

**Comment by KevinGutowski** [comment]
Gonna close this Pull request since I haven’t worked on this in a while. Might pick it back up another time though.

**Pull request closed without merging**
